const $=id=>document.getElementById(id);
const DPI=600, STORE='zebra_pestanas_datos', STORE_TAB='zebra_tab_activa_id', TEXT_STORE='zebra_text_history_v1';
let pestañas=[{id:'tab-1',nombre:'REGISTRO 1',datos:[]}], tabActivaId='tab-1', selectedIndex=null, duplicateTabId=null, duplicateIndex=null, ultimoRender={sn:'',ua:''};
let modoSeleccionMultiple=false, selecciones=new Map(), historialTextos=[];
const inputSN=$('text-sn'), inputUA=$('text-ua'), snError=$('sn-error'), modal=$('export-modal');
const textInput=$('text-label-input'), textPreview=$('text-preview-content'), textPreviewBox=$('text-label-preview'), printText=$('print-text-content');

function tabActiva(){return pestañas.find(t=>t.id===tabActivaId)||pestañas[0]}
function digitsUA(v){return String(v||'').replace(/\D/g,'').slice(0,16)}
function formatUA(v){const d=digitsUA(v),p=[];if(d)p.push(d.slice(0,3));if(d.length>3)p.push(d.slice(3,8));if(d.length>8)p.push(d.slice(8,13));if(d.length>13)p.push(d.slice(13,16));return p.join('-')}
function normSN(v){return String(v||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,12)}
function validSN(v){return /^M[A-Z0-9]{11}$/.test(v)}
function save(){localStorage.setItem(STORE,JSON.stringify(pestañas));localStorage.setItem(STORE_TAB,tabActivaId)}
function load(){try{const x=JSON.parse(localStorage.getItem(STORE)||'null');if(Array.isArray(x)&&x.length)pestañas=x}catch{} const id=localStorage.getItem(STORE_TAB);if(id&&pestañas.some(t=>t.id===id))tabActivaId=id}
function selSet(id=tabActivaId){if(!selecciones.has(id))selecciones.set(id,new Set());return selecciones.get(id)}
function recordKey(x){return `${x.sn}|${digitsUA(x.ua)}`}
function escapeHtml(value){return String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#039;')}

function renderTabs(){const c=$('tabs-header');c.innerHTML='';pestañas.forEach(t=>{const d=document.createElement('div');d.className='tab-item '+(t.id===tabActivaId?'active ':'')+(t.id===duplicateTabId?'tab-duplicate-alert':'');const n=document.createElement('span');n.textContent=`${t.nombre} (${t.datos.length})`;n.onclick=()=>t.id===tabActivaId?renameTab(t.id):switchTab(t.id);n.ondblclick=e=>{e.stopPropagation();renameTab(t.id)};d.appendChild(n);if(pestañas.length>1){const x=document.createElement('span');x.className='close-tab';x.innerHTML='&times;';x.onclick=e=>{e.stopPropagation();deleteTab(t.id)};d.appendChild(x)}c.appendChild(d)});const b=document.createElement('button');b.className='btn-add-tab';b.textContent='+';b.onclick=addTab;c.appendChild(b)}
function renameTab(id){const t=pestañas.find(x=>x.id===id),n=prompt('Nuevo nombre:',t.nombre);if(n&&n.trim()){t.nombre=n.trim().toUpperCase();save();renderTabs()}}
function addTab(){const id='tab-'+Date.now();pestañas.push({id,nombre:`REGISTRO ${pestañas.length+1}`,datos:[]});switchTab(id)}
function deleteTab(id){if(pestañas.length<2||!confirm('¿Eliminar esta pestaña y sus registros?'))return;pestañas=pestañas.filter(t=>t.id!==id);selecciones.delete(id);if(tabActivaId===id)tabActivaId=pestañas[0].id;selectedIndex=tabActiva().datos.length?0:null;save();renderTabs();renderHistory()}
function switchTab(id){tabActivaId=id;selectedIndex=tabActiva().datos.length?0:null;save();renderTabs();renderHistory();if(selectedIndex!==null)loadRecord(tabActiva().datos[selectedIndex])}
function loadRecord(x){inputSN.value=x.sn;inputUA.value=x.ua;inputSN.classList.add('valid');inputUA.classList.add('valid');renderBarcode(x.sn,x.ua)}

function renderHistory(){const t=tabActiva(),list=$('history-list'),set=selSet();const valid=new Set(t.datos.map(recordKey));[...set].forEach(k=>{if(!valid.has(k))set.delete(k)});$('btn-save-json').disabled=!pestañas.some(x=>x.datos.length);$('btn-export-unified').disabled=!t.datos.length;$('btn-clear-all').disabled=!t.datos.length;
if(!t.datos.length){list.innerHTML='<li class="empty-msg" style="padding:15px;text-align:center;">No hay registros en esta pestaña</li>';$('btn-replace-selected').disabled=true;$('btn-delete-selected').disabled=true;updateSelectCount();return}
list.innerHTML='';t.datos.forEach((x,i)=>{const li=document.createElement('li');const key=recordKey(x);li.className='history-item '+(i===selectedIndex?'selected ':'')+(duplicateTabId===tabActivaId&&i===duplicateIndex?'duplicate-alert ':'')+(modoSeleccionMultiple?'with-checkbox ':'')+(set.has(key)?'multi-checked':'');if(modoSeleccionMultiple){const cb=document.createElement('input');cb.type='checkbox';cb.className='record-select-checkbox';cb.checked=set.has(key);cb.onclick=e=>e.stopPropagation();cb.onchange=()=>{cb.checked?set.add(key):set.delete(key);renderHistory()};li.appendChild(cb)}const c=document.createElement('div');c.className='history-item-content';c.innerHTML=`<div class="history-title">${duplicateTabId===tabActivaId&&i===duplicateIndex?'⚠️ CÓDIGO DUPLICADO':'Registro #'+(t.datos.length-i)}</div><div class="history-codes"><b>SN:</b> ${escapeHtml(x.sn)}<br><b>UA:</b> ${escapeHtml(x.ua)}</div>`;li.appendChild(c);li.onclick=()=>{selectedIndex=i;loadRecord(x);renderHistory()};list.appendChild(li)});$('btn-replace-selected').disabled=selectedIndex===null;$('btn-delete-selected').disabled=selectedIndex===null;updateSelectCount()}
function updateSelectCount(){$('multi-select-count').textContent=modoSeleccionMultiple?`${selSet().size} seleccionado${selSet().size===1?'':'s'}`:''}
$('toggle-record-checkboxes').onchange=e=>{modoSeleccionMultiple=e.target.checked;if(!modoSeleccionMultiple)selSet().clear();renderHistory()};

inputSN.oninput=function(){this.value=normSN(this.value);const ok=validSN(this.value),start=!this.value||this.value.startsWith('M');this.classList.toggle('valid',ok);this.classList.toggle('invalid',!start);snError.textContent=start?'':'ERROR: el Host SN debe comenzar con M.';if(ok){inputUA.focus();inputUA.select()}autoGenerate()};
inputUA.oninput=function(){this.value=formatUA(this.value);this.classList.toggle('valid',digitsUA(this.value).length===16);autoGenerate()};
function autoGenerate(){if(validSN(inputSN.value)&&digitsUA(inputUA.value).length===16)generate(true)}
function resetInputs(){inputSN.value='';inputUA.value='';inputSN.classList.remove('valid','invalid');inputUA.classList.remove('valid');snError.textContent='';inputSN.focus()}

function printStyle(w,h){let s=$('dynamic-print-style');if(!s){s=document.createElement('style');s.id='dynamic-print-style';document.head.appendChild(s)}s.textContent=`@media print{@page{margin:0;size:${w}in ${h}in}html,body,#print-area{width:${w}in!important;height:${h}in!important;margin:0!important;padding:0!important;overflow:hidden!important}#print-barcode-content{padding:.025in .055in!important;box-sizing:border-box!important}#print-text-label{padding:1.5mm 3mm!important;box-sizing:border-box!important}}`}
function barcodeParams(w,h){const compact=h<=1,scale=Math.sqrt(DPI/203),ws=Math.max(1,w/2.5);return compact?{bh1:54,bh2:50,fs1:19,fs2:17,m1:Math.min(2.15,1.75*ws*scale),m2:Math.min(2.25,1.95*ws*scale),q:7}:{bh1:90,bh2:82,fs1:28,fs2:25,m1:Math.min(4,2.4*ws*scale),m2:Math.min(4,2.5*ws*scale),q:10}}
function renderBarcode(sn,ua){const d=digitsUA(ua);if(!validSN(sn)||d.length!==16)return;const [w,h]=$('select-size').value.split('x').map(Number),p=barcodeParams(w,h);ultimoRender={sn,ua:formatUA(d)};printStyle(w,h);const base={format:'CODE128',lineColor:'#000',displayValue:true,fontOptions:'bold',font:'Arial',textAlign:'center',background:'#fff'};const o1={...base,width:p.m1,height:p.bh1,fontSize:p.fs1,textMargin:2,margin:p.q,text:'Host SN: '+sn};const o2={...base,width:p.m2,height:p.bh2,fontSize:p.fs2,textMargin:2,margin:p.q,text:'UA: '+formatUA(d)};JsBarcode('#display-sn',sn,o1);JsBarcode('#display-ua',d,o2);JsBarcode('#print-sn',sn,o1);JsBarcode('#print-ua',d,o2);$('btn-download').disabled=false;$('btn-print-main').disabled=false}
function findDuplicate(sn,ua,ignore=null){const d=digitsUA(ua);for(const t of pestañas){const i=t.datos.findIndex((x,j)=>!(ignore&&ignore.tab===t.id&&ignore.index===j)&&(x.sn===sn||digitsUA(x.ua)===d));if(i>=0)return{tab:t,index:i,item:t.datos[i]}}return null}
function flashDuplicate(x){duplicateTabId=x.tab.id;duplicateIndex=x.index;renderTabs();renderHistory();setTimeout(()=>{duplicateTabId=null;duplicateIndex=null;renderTabs();renderHistory()},4000)}
function generate(store=true){const sn=normSN(inputSN.value),ua=formatUA(inputUA.value);if(!validSN(sn)||digitsUA(ua).length!==16)return;renderBarcode(sn,ua);if(!store)return;const dup=findDuplicate(sn,ua);if(dup){flashDuplicate(dup);resetInputs();return}tabActiva().datos.unshift({sn,ua,fecha:new Date().toLocaleDateString(),hora:new Date().toLocaleTimeString()});selectedIndex=0;save();renderTabs();renderHistory();resetInputs()}

$('btn-replace-selected').onclick=()=>{const t=tabActiva();if(selectedIndex===null||!t.datos[selectedIndex])return;const sn=normSN(inputSN.value),ua=formatUA(inputUA.value);if(!validSN(sn)||digitsUA(ua).length!==16){alert('Host SN inválido o UA incompleto.');return}const dup=findDuplicate(sn,ua,{tab:t.id,index:selectedIndex});if(dup){alert(`ERROR: Host SN o UA ya existe en ${dup.tab.nombre}.`);flashDuplicate(dup);return}t.datos[selectedIndex]={sn,ua,fecha:new Date().toLocaleDateString(),hora:new Date().toLocaleTimeString()};save();renderTabs();renderHistory();renderBarcode(sn,ua);resetInputs()};
$('btn-delete-selected').onclick=()=>{const t=tabActiva();if(selectedIndex===null)return;selSet().delete(recordKey(t.datos[selectedIndex]));t.datos.splice(selectedIndex,1);selectedIndex=t.datos.length?0:null;save();renderTabs();renderHistory();if(selectedIndex!==null)loadRecord(t.datos[0])};
$('btn-clear-all').onclick=()=>{if(confirm('¿Vaciar la pestaña actual?')){tabActiva().datos=[];selSet().clear();selectedIndex=null;save();renderTabs();renderHistory()}};

function safeName(s){return String(s||'REGISTRO').replace(/[\\/:*?"<>|]/g,'_')}
function exportExcel(){const t=tabActiva();if(!t.datos.length)return;const rows=[...t.datos].reverse().map((x,i)=>({'Nº':i+1,'UNIT ADDRESS':x.ua,'SERIAL':x.sn,'Fecha':x.fecha,'Hora':x.hora}));const wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(rows);XLSX.utils.book_append_sheet(wb,ws,safeName(t.nombre).slice(0,31));XLSX.writeFile(wb,`Reporte_Zebra_${safeName(t.nombre)}_${new Date().toISOString().slice(0,10)}.xlsx`)}
function exportTXT(){const t=tabActiva();if(!t.datos.length)return;let c=`PESTAÑA: ${t.nombre}\n\n`;[...t.datos].reverse().forEach((x,i)=>c+=`${i+1}. SERIAL: ${x.sn} | UNIT ADDRESS: ${x.ua}\n`);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([c],{type:'text/plain;charset=utf-8'}));a.download=`Reporte_Zebra_${safeName(t.nombre)}_${new Date().toISOString().slice(0,10)}.txt`;a.click();URL.revokeObjectURL(a.href)}
$('btn-export-unified').onclick=()=>modal.style.display='flex';$('btn-modal-close').onclick=()=>modal.style.display='none';$('btn-modal-excel').onclick=()=>{exportExcel();modal.style.display='none'};$('btn-modal-txt').onclick=()=>{exportTXT();modal.style.display='none'};window.addEventListener('click',e=>{if(e.target===modal)modal.style.display='none'});

$('btn-save-json').onclick=()=>{if(!pestañas.some(t=>t.datos.length))return;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({version:'3.0',fechaExportacion:new Date().toISOString(),tabActivaId,pestanas:pestañas},null,2)],{type:'application/json'}));a.download=`Sesion_Zebra_${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};
$('btn-load-json').onclick=()=>$('file-input-json').click();$('file-input-json').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(x&&Array.isArray(x.pestanas)&&x.pestanas.length){pestañas=x.pestanas;tabActivaId=pestañas.some(t=>t.id===x.tabActivaId)?x.tabActivaId:pestañas[0].id}else if(Array.isArray(x))tabActiva().datos=x;else throw 0;selectedIndex=tabActiva().datos.length?0:null;save();renderTabs();renderHistory();if(selectedIndex!==null)loadRecord(tabActiva().datos[0]);alert('Sesión cargada correctamente.')}catch{alert('JSON no válido.')}e.target.value=''};r.readAsText(f)};

$('select-size').onchange=()=>{if(ultimoRender.sn)renderBarcode(ultimoRender.sn,ultimoRender.ua)};
$('btn-print-main').onclick=()=>{if(!ultimoRender.sn)return;const [w,h]=$('select-size').value.split('x').map(Number);renderBarcode(ultimoRender.sn,ultimoRender.ua);document.body.classList.remove('print-mode-text');document.body.classList.add('print-mode-barcode');printStyle(w,h);window.print()};
$('btn-download').onclick=()=>{if(!ultimoRender.sn)return;const [w,h]=$('select-size').value.split('x').map(Number),canvas=$('export-canvas'),ctx=canvas.getContext('2d');canvas.width=Math.round(w*DPI);canvas.height=Math.round(h*DPI);ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);const svgs=[$('print-sn'),$('print-ua')],imgs=[];Promise.all(svgs.map(svg=>new Promise((res,rej)=>{const url=URL.createObjectURL(new Blob([new XMLSerializer().serializeToString(svg)],{type:'image/svg+xml'})),im=new Image();im.onload=()=>{URL.revokeObjectURL(url);imgs.push(im);res()};im.onerror=rej;im.src=url}))).then(()=>{const slot=canvas.height/2;imgs.forEach((im,i)=>{const sc=Math.min(canvas.width*.96/im.width,slot*.94/im.height),dw=im.width*sc,dh=im.height*sc;ctx.drawImage(im,(canvas.width-dw)/2,i*slot+(slot-dh)/2,dw,dh)});const a=document.createElement('a');a.download=`Etiqueta_${ultimoRender.sn}_${digitsUA(ultimoRender.ua)}.png`;a.href=canvas.toDataURL('image/png');a.click()})};

function textConfig(){const [w,h]=$('text-select-size').value.split('x').map(Number);return{w,h,align:$('text-label-align').value,weight:$('text-label-weight').value,max:$('text-label-max-size').value}}
function fitText(el,box,maxPt){let pt=maxPt;el.style.fontSize=pt+'pt';while(pt>5&&(el.scrollWidth>box.clientWidth||el.scrollHeight>box.clientHeight)){pt-=.5;el.style.fontSize=pt+'pt'}return pt}
function updateTextPreview(){const txt=textInput.value, cfg=textConfig();textPreviewBox.style.aspectRatio=`${cfg.w}/${cfg.h}`;textPreview.textContent=txt.trim()?txt:'VISTA PREVIA DEL TEXTO';textPreview.style.textAlign=cfg.align;textPreview.style.fontWeight=cfg.weight;const max=cfg.max==='auto'?Math.min(72,Math.max(18,cfg.h*36)):Number(cfg.max);requestAnimationFrame(()=>fitText(textPreview,textPreviewBox,max));$('btn-print-text').disabled=!txt.trim();$('btn-save-text-history').disabled=!txt.trim()}
['text-select-size','text-label-align','text-label-weight','text-label-max-size'].forEach(id=>$(id).onchange=updateTextPreview);textInput.oninput=updateTextPreview;
function loadTextHistory(){try{const x=JSON.parse(localStorage.getItem(TEXT_STORE)||'[]');historialTextos=Array.isArray(x)?x:[]}catch{historialTextos=[]}renderTextHistory()}
function saveTextHistory(silent=false){const txt=textInput.value.trim();if(!txt)return;const cfg=textConfig(),key=txt.toLowerCase();historialTextos=historialTextos.filter(x=>x.texto.toLowerCase()!==key);historialTextos.unshift({id:Date.now(),texto:txt,size:`${cfg.w}x${cfg.h}`,align:cfg.align,weight:cfg.weight,max:cfg.max,fecha:new Date().toLocaleDateString(),hora:new Date().toLocaleTimeString()});historialTextos=historialTextos.slice(0,60);localStorage.setItem(TEXT_STORE,JSON.stringify(historialTextos));renderTextHistory();if(!silent)alert('Texto guardado.')}
function renderTextHistory(){const list=$('text-history-list');$('text-history-count').textContent=historialTextos.length;$('btn-clear-text-history').disabled=!historialTextos.length;if(!historialTextos.length){list.innerHTML='<div class="text-history-empty">Todavía no hay textos guardados.</div>';return}list.innerHTML='';historialTextos.forEach(x=>{const d=document.createElement('div');d.className='text-history-item';const m=document.createElement('div');m.className='text-history-main';m.innerHTML=`<div class="text-history-text"></div><div class="text-history-meta">${x.fecha||''} ${x.hora||''}</div>`;m.querySelector('.text-history-text').textContent=x.texto;const a=document.createElement('div');a.className='text-history-item-actions';const u=document.createElement('button');u.className='btn-use-text-history';u.textContent='USAR';u.onclick=()=>useText(x);const del=document.createElement('button');del.className='btn-delete-text-history';del.textContent='ELIMINAR';del.onclick=()=>{historialTextos=historialTextos.filter(y=>y.id!==x.id);localStorage.setItem(TEXT_STORE,JSON.stringify(historialTextos));renderTextHistory()};a.append(u,del);d.append(m,a);list.appendChild(d)})}
function useText(x){textInput.value=x.texto;$('text-select-size').value=x.size||'2.5x1.0';$('text-label-align').value=x.align||'center';$('text-label-weight').value=x.weight||'700';$('text-label-max-size').value=x.max||'auto';updateTextPreview();textInput.focus()}
$('btn-save-text-history').onclick=()=>saveTextHistory(false);$('btn-clear-text-history').onclick=()=>{if(confirm('¿Vaciar historial de textos?')){historialTextos=[];localStorage.removeItem(TEXT_STORE);renderTextHistory()}};
function prepText(){const txt=textInput.value.trim();if(!txt)return false;const cfg=textConfig();printStyle(cfg.w,cfg.h);printText.textContent=txt;printText.style.textAlign=cfg.align;printText.style.fontWeight=cfg.weight;printText.style.fontFamily='Arial,sans-serif';const max=cfg.max==='auto'?Math.min(72,Math.max(18,cfg.h*36)):Number(cfg.max);printText.style.fontSize=max+'pt';return true}
$('btn-print-text').onclick=()=>{if(!prepText())return;saveTextHistory(true);document.body.classList.remove('print-mode-barcode');document.body.classList.add('print-mode-text');window.print()};

function switchMain(v){const text=v==='text';$('view-barcode').classList.toggle('active',!text);$('view-text').classList.toggle('active',text);document.querySelectorAll('.main-nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===v));localStorage.setItem('zebra_main_view',v);if(text)updateTextPreview()}
document.querySelectorAll('.main-nav-btn').forEach(b=>b.onclick=()=>switchMain(b.dataset.view));

window.onload=()=>{document.body.classList.add('print-mode-barcode');load();renderTabs();renderHistory();if(tabActiva().datos.length){selectedIndex=0;loadRecord(tabActiva().datos[0])}loadTextHistory();updateTextPreview();switchMain(localStorage.getItem('zebra_main_view')==='text'?'text':'barcode')};
